# Generated by Django 4.1.1 on 2022-10-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_problem_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='upvote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
