# Generated by Django 4.1.1 on 2022-10-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_problem_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
