# Generated by Django 4.1.1 on 2022-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_problem_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
