# Generated by Django 4.1.1 on 2022-11-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
