# Generated by Django 4.1.1 on 2022-11-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_user_userip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='problem',
            name='iptracker',
            field=models.JSONField(default=''),
        ),
    ]
