# Generated by Django 4.1.1 on 2022-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_problem_iptracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='iptracker',
            field=models.JSONField(default=''),
        ),
    ]
