# Generated by Django 4.1.1 on 2022-12-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_problem_iptracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
