# Generated by Django 4.1.1 on 2022-12-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_problem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
