# Generated by Django 4.1.1 on 2022-12-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_problem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
